---
title: "Fall 2025 Reflections: Probability & Statistics I"
description: "End of semester reflections on a probability theory course"
author: "Jessie Oehrlein"
date: "12/28/2025"
draft: false

categories:
  - probability
  - teaching
  - end of semester
---

This was my easiest prep of the semester. Format-wise, I was doing something a bit different than the previous two times I had taught the course, but I was using more or less the same sheets of problems as a basis. I enjoyed working with this group of students, and seeing them get to know each other and work increasingly collaboratively as the semester went on was a delight.

In previous semesters, I'd had almost almost all work on problems happening outside of class and almost all in-class time being dedicated to presentations, and then students would write up selected problems more formally and submit those. This time, I moved some problem work time to be in class. We'd start with presentations of what they'd done between classes, and then we'd move into time for them to work on the next few problems. This was in response to a couple of things. Student reflections from previous semesters had mentioned that they would have liked more chances in class to work together on problems, so this was taking that feedback directly. But I also hoped that this would "even out" some of the differences I'd seen in how comfortable students were with problem-solving and proofs.

I think this was successful in terms of student enjoyment and comfort, and I think it did a better job of getting everyone in the course to a certain level of facility with the material. It was also substantially slower. I was not too worried about this early on in the semester, content with going at the pace of the students in an upper-level course. With about a month left I realized that I had a problem, and I started shortening sheets, not having students present everything they'd worked on, not assigning all exercises, etc., just so that we could actually get through the content that I think is necessary in an undergrad prob theory course. I needed to be making some of those decisions (especially around presenting everything) to a lesser extent all along.

Maybe more importantly, I need to think about how I can kick-start everything that happens in class. We were in a whiteboard wall classroom, so for presentations I would let everyone put work up on the board at once and then present sequentially. That seems like it should be faster than just going up to boards one-by-one, and maybe it was, but it still felt like a lot of kind-of-dead time when different problems take different times to write up. And I know there used to be dead time as people wrote things before talking one-by-one! Or they would write as they went, and it wasn't quite as clear. (Though maybe being able to do that well is a more valuable skill to have? I'm not sure.) I have similar "how to get this going" feelings about the problem-solving they do in class. I did a lot of giving folks a few minutes to think and work individually and then asking them to form pairs or trios, but that process was often slow to get going.

Differentiation is also something I'm frequently thinking about in this course. In the other upper-level course I taught this semester, everything is built around projects with a lot of student choice, so it's relatively straightforward to scale a project to a student's mix of background, interest, investment, and available time/energy. I labeled a few problems in this course as challenge problems, which were always options for writeups, but they were never officially assigned and weren't discussed in class. I'm wondering if incorporating more of those throughout all the sets is the right way to go to provide more to think about. It allows some tailoring of the out-of-class experience (though it's still "do these easier things and then here's this chewier thing if you get there," which isn't always great) but it doesn't adjust the in-class experience at all.

A student also pointed out that a lot of the applied problems were still rather idealized scenarios in terms of matching well to a type of random variable, having known parameters, etc. This is valid, though I see it to some extent as falling out of this being a probability course and not a statistics course. (As soon as you're trying to figure out parameters using data, you're doing statistics.) But there is definitely room for application questions that are a little more involved while still being idealized, or where there's more to figure out, in some sense. I could also write more formally into the sheets some of the things I do more informally in class --- asking about assumptions, comparing multiple approaches, etc.

Writeups continued to work pretty well, and I could see student writing developing over the course of the semester. I was able to tailor feedback a bit to where students were, why they were taking the class, etc. That said, I'm scheduled to teach this again next fall, and I'm hoping to nail down clearer expectations and potential growth directions for both presentations and writeups. I'm not planning on changing the fact that presentations aren't graded, but we're trying to focus more as a department on developing students' presentation skills. On the writeup side, I both want clearer and more consistent specifications for grading purposes and also more thought about directions I can take feedback for students who already solid mathematical writers.

The project that I finish the semester with also would benefit from some of that better definition. Students mostly get to the right scope with the information I give them now, but it would be better to be more explicit. The options I'm giving for the project are definitely working well, though! It was nice to end the semester with a mix of exploration of further probability topics and fun applications of ideas to games and puzzles.
