project:
  type: website
  output-dir: docs

website:
  title: "Jessie Oehrlein"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

