project:
  type: website
  output-dir: docs

website:
  title: "Jessie Oehrlein"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: service.qmd
        text: Service
      - href: enrichment.qmd
        text: Enrichment
      - href: fun.qmd
        text: Fun
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

