---
title: "Enrichment Teaching"
page-layout: full
---

In addition to college-level teaching, I've done a variety of K-12 enrichment teaching. Select examples are below.

This page is under construction.

# Classes Taught at NMC Camp Conway

National Math Camps is an organization that currently runs two locations of two-week summer math camps for 11-14 year olds. I will spend two weeks teaching at Camp Conway in summer 2026.

## Dynamical Systems

Dynamical Systems will focus on the behavior and applications of (mostly one-dimensional) discrete dynamical systems.

## Algorithms

Algorithms will focus on what makes something a "good" algorithm, some common sorting and graph algorithms, and their applications/extensions.

# Classes Taught at MathPath

MathPath is a four-week summer math camp for 11-14 year olds. I spent one week teaching at MathPath in summer 2022 and will spend two weeks there in summer 2026.

## Climate and Chaos

Climate and Chaos was a class focused on discrete dynamical systems with connections to Earth's atmosphere, especially energy balance models, atmospheric stability, and convection.

Related materials: sample homeworks

## The Amazing Algorithmic Race

This was a class focused on developing and evaluating algorithms. The class started with activities exploring what a good algorithm is and then moved into developing sorting and graph search algorithms, looking at big-O notation along the way. One of my favorite moments of the course in Summer 2022 was students coming up with the idea of log base 2 themselves in order to talk about what was happening in mergesort.

Related materials: sample homeworks

## Graph Coloring

To be developed (summer 2026)!

## Bayesian Statistics

To be developed (summer 2026)!

# Classes Taught at Learning Unlimited Programs

## Bridges, Maps, and Networks

This class covers Eulerian walks/circuits, the Five-Color Theorem, and some basic ideas in network science to provide an overview of different areas of graph theory. With the exception of the proof of the Five-Color Theorem, the main ideas of the class typically come from students \-- figuring out why a graph does or doesn't have an Eulerian walk, finding a counterexample to a "Three-Color Conjecture," proposing ways to measure how central a vertex is in a network.

Links to related materials: JMM presentation slides, [blog posts](https://mathinthesky.wordpress.com/tag/bridges-maps-networks/).

## How to (Mathematically) Guard an Art Gallery

This class covers a proof of the Art Gallery Theorem, using ideas about triangles, graph duals, trees, and graph coloring.

Links to related materials: JMM presentation slides, [blog posts](https://mathinthesky.wordpress.com/tag/art-gallery/).

## Introduction to Mathematical Modeling

This class introduces students to a mathematical modeling process. Two of the problems I use (one about selecting a computer, one about where a taco truck should park) come from the [GAIMME Report](https://www.comap.com/Free/GAIMME/index.html). We also discuss earlier steps in the modeling process with a disease as the context: what might we want to know, and what features might we want in a model to address those different questions?

Links to related materials: [blog posts](https://mathinthesky.wordpress.com/tag/intro-math-modeling/).

## Other Mathematical Modeling Courses

**Population Modeling:** This class evolved out of student comments on the Intro Math Modeling class, expressing interest in more advanced modeling material. It is mainly structured around group activities exploring different kinds of populations and their dynamics, modeled with compartmental models.

Links to related materials: [sample activities](https://mathinthesky.files.wordpress.com/2019/03/population_modeling_problems.pdf), [JMM presentation slides](https://mathinthesky.files.wordpress.com/2019/03/jmm2019_presentation.pdf), [blog posts](https://mathinthesky.wordpress.com/tag/population-modeling/).

**Disease Modeling:** This class was another attempt to provide a more advanced modeling class. I structure the class around a game (which I learned from Brian Hollenbeck) and connect that game to an SIR model.

Links to related materials: [blog posts](https://mathinthesky.wordpress.com/tag/disease-modeling/).

## Ballet History

**From Swans to Spartacus, Ballet in the Soviet Union:** This class covers mainly the Bolshoi and Kirov from the 1920s through 1970s, with emphases on the dramballet, ballets with revolutionary themes, and the sustained presence and cultural importance of classical works.

**History of Ballet, 1900 - Present:** This class covers ballet in the 20th century (with a touch of the present at the end) in the US, UK, Russia/Soviet Union, and continental Europe, trying to provide a flavor of the wide variety of styles that were prominent or developed during the period.

# TAing at Art of Problem Solving

I was a teaching assistant and grader for Art of Problem Solving online courses from 2012 through 2020. Over that period, I was a frequent assistant for many intro level courses in math and programming, and I assisted most intermediate courses at some point, as well. I enjoyed getting to see, respond to, and discuss the wide variety of student thinking in a fast-paced, text-based, synchronous environment.
