---
title: "Fun"
page-layout: full
---

This page is under construction.

## Roller Coasters

My current favorite wooden roller coasters are:

1.  Voyage at Holiday World

2.  El Toro at Six Flags Great Adventure

3.  GhostRider at Knott's Berry Farm

My current favorite steel roller coasters are:

1.  Millennium Force at Cedar Point

2.  Iron Gwazi at Busch Gardens Tampa

3.  Nitro at Six Flags Great Adventure

## Dance

### Watching Dance

My current "home" ballet companies are Boston Ballet (in person) and Pacific Northwest Ballet (virtually). At points in the past my home companies have included New York City Ballet, American Ballet Theatre, Oklahoma City Ballet/Ballet Oklahoma, and Tulsa Ballet.

Some of my favorite companies, choreographers, and dancers in other areas of dance include Alvin Ailey American Dance Theater, Jose Limon Dance Company, Dorrance Dance, Parsons Dance Company, Ayodele Casel, Dormeshia Sumbry-Edwards, Music from the Sole, Pam Tanowitz, the Gardiner Brothers, Harini Nilakantan, and Kara Chan.

Some favorite pieces:

-   **Story ballet:** Coppelia, the story of a girl, her boyfriend, the other girl-but-actually-doll he thinks is pretty, and an old dollmaker. Some very weird and questionable things happen, but there's a lot of great dancing and acting.

-   **Non-story ballet:** Square Dance by George Balanchine. What if Vivaldi + classical movement inspired by square dance + sometimes a caller.

-   **Non-story ballet:** NY Export: Opus Jazz by Jerome Robbins. The definition of a sneaker ballet and Robbins's ability to get dancers dancing to each other instead of the audience.

-   **Have seen the most (other than Nutcracker):** Romeo & Juliet, 17 times across versions by 12 different choreographers. I have Opinions about the ending, the portrayal of the feud, and character and relationship arcs across pas de deux.

-   The piece of dance that has most lived in my brain for years after seeing it (not even live!) is **Michelle Dorrance's "New to the Session"** (music by Rhiannon Giddens) from the Vail Dance Festival.

### Dancing

At various points I've studied ballet, jazz, Horton-style modern, and Limon-style modern. One of the things I liked most about living in New York was being able to try different specific styles of modern to find what really "fit" the way I like to move.

I also learned some salsa and east-coast and west-coast swing (but more salsa than swing) at summer camps. I continued to do salsa informally and occasionally in college.

But the other style that I learned at summer camp was contra dance, which is what you'll most commonly find me dancing now. I love learning the patterns, dancing with lots of people, and the sheer joy of the music and the dance.

## Sports

I watch a *wide* variety of sports. Sports I actively and consistently follow include baseball, softball, gymnastics, figure skating, curling, tennis, sport climbing, fencing, and football.

Some of my favorites:

-   **Baseball**: Houston Astros (MLB), TCU Horned Frogs (college D1), Babson Beavers (college D3)

-   **Softball**: OU Sooners (college D1), Oklahoma City Spark (AUSL)

-   **Artistic Gymnastics**: OU Sooners men and women (college D1), Clemson Tigers (college D1), Rebeca Andrade, Joscelyn Roberson, Kaylia Nemour, Kaliya Lincoln, Tonya Paulsson, Levi Jung-Ruivivar, Chloe Lacoursiere, Jayla Hang, Aiko Sugihara, Jess Gadirova, Khoi Young, Jake Jarman, Yul Moldauer

-   **Trampoline & Tumbling:** Ruben Padilla, Gracie Harder, Kaden Brown

-   **Figure Skating**: Yuma Kagiyama, Yuna Aoki, Loicia Demougeot/Theo Le Mercier, Caroline Green/Michael Parsons, Alysa Liu, Amber Glenn

-   **Curling**: Team Homan, Team St-Georges, Thiesse/Dropkin

-   **Tennis**: Carlos Alcaraz, Iga Swiatek, Coco Gauff, Jasmine Paolini, Cam Norrie, Sara Errani

-   **Climbing**: Janja Garnbret, Natalia Grossman, Brooke Raboutou, Annie Sanders, Oriane Bertone, Mao Nakamura, Ai Mori, Hannah Meul, Oceana Mackenzie, Sorato Anraku, Toby Roberts, Mejdi Schalck

-   **Fencing**: The US foilists

-   **Football**: TCU Horned Frogs (college D1)

If you are interested in some of my favorite figure skating performances, you can watch some on [this YouTube playlist](https://youtube.com/playlist?list=PLJ6NftQtdym86MtmaeumYOOMoJjbq_5-p&si=v2FN26Flr_X_Fihc).

## Books

(put some favorite books here)

## Cross Stitch and Blackwork

(put some photos here)
